### ISSUE TITLE
テスト版GUIのエラー時の処理について

### ISSUE THREAD

**Issue by xrun-rounz1** [Yui0471/VRChat_OSC_Clock_System#3]
不正なIPアドレスやポート番号が渡された際の処理についてです。

現在は、エラーの際は``127.0.0.1:9000``に自動的に設定されスタートされます。
しかし、その場合予期しないポートに通信してしまう可能性があるのではないでしょうか。
そのため、自動的に設定するのみでスタートはしないほうがいいかと思われます。

**Comment by Yui0471** [comment]
ありがとうございますー！
とりあえずの処置ですが、関数の戻り値にタプルでbool値を返すようにしました。
戻り値の真偽を元に実行するかどうか判別するようにしています。
多分もっと良い方法があると思うので、思いついたらそのうち修正しますね……()

**Comment by xrun-rounz1** [comment]
提案があります。

現在、ここの部分でエラーを判定していると思います。

https://github.com/Yui0471/VRChat_OSC_Clock_System/blob/9d4ba119fcb5a28030a855572fde567f94694f6c/Analog_Clock_System_Stable_V2/script/ACS_OSC_Clock-GUI.py#L361-L370
しかし、check関数にてフィールドに正しい値がセットされ、タプルの０番要素は使用されていないので
下のコードのように``ip_check``,``port_check``,``interval_check``にてNoneを返すようにするのはどうでしょうか

```py
sg.popup("エラーが発生しました！\n【このIPは使用できません】")
return None 
```

**Comment by Yui0471** [comment]
なるほど……！　ありがとうございます！
最新のコミットで反映させていただきました。
https://github.com/Yui0471/VRChat_OSC_Clock_System/blob/423a39c729873b9518b2a87c7a609e6c9ca754ea/Analog_Clock_System_Stable_V2/script/ACS_OSC_Clock-GUI.py#L364-L368

こうすることで簡潔に見やすくなるんですね……すごい……。
ありがとうございます！
